server:
  port: 9090
logging:
  level:
    root: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb+srv://evento_admin:evento_admin@cluster0.01whe.mongodb.net/EmployeeManagementDB?retryWrites=true&w=majority
      database: EmployeeManagementDB